name: MiniWDL Conformance - WDL 1.1

on:
  push:
  pull_request:

jobs:
  conformance:
    runs-on: ubuntu-latest
    name: Run WDL 1.1 Conformance Tests (MiniWDL - Structs)

    steps:
      - name: Checkout WDL spec repo (wdl-1.1)
        uses: actions/checkout@v4
        with:
          repository: openwdl/wdl
          ref: wdl-1.1
          path: wdl-spec

      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install MiniWDL and dependencies
        run: |
          pip install miniwdl junit-xml subby

      - name: Clone WDL tests
        run: |
          git clone https://github.com/openwdl/wdl-tests.git

      - name: Extract tests
        run: |
          python wdl-tests/scripts/extract_tests.py -i ./SPEC.md -d ./tests/data/ -O miniwdl_test -v 1.1
      
      - name: Run tests
        run: |
          python wdl-tests/scripts/run_tests_miniwdl.py -T ./miniwdl_test -c ./miniwdl_test/test_config.json -D ./miniwdl_test/data -O miniwdl_tests -n 1      
